on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: Enable Debugging

name: 🧪 Tests

jobs:
  run-tests:
    strategy:
      fail-fast: false

      matrix:
        backend:
          - Qt5
          - Qt6
          - WebKitGtk
          - WebKit

        config:
          - Release
          - Debug

        include:
          - backend: Qt5
            platform: Linux
            os: ubuntu-latest
            container: archlinux:base-devel

          - backend: Qt6
            platform: Linux
            os: ubuntu-latest
            container: archlinux:base-devel

          - backend: WebKitGtk
            platform: Linux
            os: ubuntu-latest
            container: archlinux:base-devel

          - backend: WebKit
            platform: MacOS
            os: macos-latest

    name: ${{ matrix.backend }}-${{ matrix.config }}

    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🛸 Setup Saucer
        uses: ./.github/actions/setup
        with:
          backend: ${{ matrix.backend }}
          platform: ${{ matrix.platform }}
          build-type: ${{ matrix.config }}
          cmake-args: -Dsaucer_tests=ON -Dsaucer_examples=ON

      - name: 🐛 Debug
        if: ${{ github.event.inputs.debug == 'true' }}
        uses: mxschmitt/action-tmate@v3
        with:
          install-dependencies: false
          limit-access-to-actor: true

      - name: 🧪 Test
        timeout-minutes: 10
        uses: ./.github/actions/test
        if: ${{ matrix.backend != 'WebKitGtk' && matrix.backend != 'WebKit' }}
